name: laguna_app
description: "Navigatore Laguna Venezia - Pro Version"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- MOTORE MAPPE ---
  flutter_map: ^6.1.0
  latlong2: ^0.9.1

  # --- POSIZIONE E SENSORI ---
  geolocator: ^11.0.0
  wakelock_plus: ^1.2.8

  # --- RETE E ICONE ---
  http: ^1.2.1
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/canali.json